name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: deps
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libavcodec-dev libavresample-dev libavformat-dev libswscale-dev libgtk-3-dev libboost-dev libeigen3-dev libtbb-dev libopencv-dev libopencv-contrib-dev
    - name: configure
      run: |
        mkdir build
        cd build
        cmake ../ -DBUILD_TESTING=ON
    - name: make
      run: cmake --build build/ 
    - name: test
      run: |
        cd build
        make test
