name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: deps
      run: |
        sudo chmod +x provisionVM.sh
        sudo ./provisionVM.sh
    - name: configure
      run: |
        mkdir build
        cd build
        cmake ../ -DBUILD_TESTING=ON
    - name: make
      run: cmake --build build/ 
    - name: test
      run: |
        cd build
        ctest -R "db_test"
