name: Test Attacks CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Workflow level environment variables
env:
  ATTACKREPO: "https://raw.githubusercontent.com/cnagda/id-pirated-vid-attackvids/master/attackvids/"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  refresh-cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: deps
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libavcodec-dev libavresample-dev libavformat-dev libswscale-dev libgtk-3-dev
    - name: Cache OpenCV
      id: cache-opencv
      uses: actions/cache@v1
      with:
        path: OpenCV # npm cache files are stored in `~/.npm` on Linux/macOS
        key: OpenCV-nofail3
    - name: OpenCV
      if: steps.cache-opencv.outputs.cache-hit != 'true'
      run: |
        mkdir $GITHUB_WORKSPACE/OpenCV
        cd $GITHUB_WORKSPACE/OpenCV
        git clone --depth=1 --branch 4.2.0 https://github.com/opencv/opencv.git
        git clone --depth=1 --branch 4.2.0 https://github.com/opencv/opencv_contrib.git
        mkdir build
        cd build
        cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local \
        -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules -D WITH_FFMPEG=ON -D WITH_OPENMP=ON \
        -DOPENCV_ENABLE_NONFREE=ON -D BUILD_EXAMPLES=OFF -WITH_GTK=ON -D BUILD_opencv_apps=OFF -D BUILD_DOCS=OFF \
        -D BUILD_PERF_TESTS=OFF -D BUILD_TESTS=OFF ../opencv
        make -j8
       
  # Query with one attack video
  query:
    needs: refresh-cache
    strategy:
      matrix:
        vid: [CNAU0235000H_exact_match.mp4, CNAU0235000H_exact_match_inserted.mp4]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: deps
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libavcodec-dev libavresample-dev libavformat-dev libswscale-dev libgtk-3-dev libboost-dev libeigen3-dev libtbb-dev
    
    - name: Cache OpenCV
      id: cache-opencv
      uses: actions/cache@v1
      with:
        path: OpenCV
        key: OpenCV-nofail3
    
    - name: Install OpenCV
      run: |
        cd $GITHUB_WORKSPACE/OpenCV/build
        sudo make install
        
    - name: configure
      run: |
        mkdir build
        cd build
        cmake ../
        
    - name: make
      run: cmake --build build/ 
    
    - name: Cache Database
      id: cache-database
      uses: actions/cache@v1
      with:
        path: id-pirated-vid-db
        key: id-pirated-vid-db-nofail

    - name: Download Database
      if: steps.cache-database.outputs.cache-hit != 'true'
      run: git clone https://github.com/cnagda/id-pirated-vid-db.git
    
    # Download the video from the attackvids repo
    - name: download video
      run: |
        echo ${ATTACKREPO}${{ matrix.vid }}
        curl -LJO ${ATTACKREPO}${{ matrix.vid }}
        ls
        mkdir results
        python3 python/tester.py ${{ matrix.vid }} id-pirated-vid-db/database > ${{ matrix.vid }}.txt
  
    - name: upload result
      uses: actions/upload-artifact@v1
      with:
        name: results
        path: ${{ matrix.vid }}.txt

  combine-results:
    needs: query
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: results

      - name: Make report
        run: ls results
